name: Generate Release Notes

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*.*.*'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Generate changelog (conventional)
        run: |
          npx conventional-changelog -p angular -i CHANGELOG.md -s
      - name: Create release artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md
      - name: Create GitHub Release Notes (update release)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
