name: Generate Release Notes

on:
  release:
    types: [published]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo fully (important for pushing)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ Generate a new RELEASE_NOTES.md file
      - name: Generate release notes file
        run: |
          echo "## Release Notes for ${GITHUB_REF_NAME}" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "- Added new features and bug fixes." >> RELEASE_NOTES.md
          echo "- Version: ${GITHUB_REF_NAME}" >> RELEASE_NOTES.md

      # 3️⃣ Commit and push the notes to main branch
      - name: Commit and push release notes to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Determine default branch dynamically (main/master/etc.)
          DEFAULT_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
          echo "Default branch is $DEFAULT_BRANCH"

          # Switch to that branch
          git checkout $DEFAULT_BRANCH

          # Copy generated notes from tag workspace
          cp -f RELEASE_NOTES.md RELEASE_NOTES.md

          git add RELEASE_NOTES.md
          git commit -m "Add release notes for ${GITHUB_REF_NAME}" || echo "No changes to commit"
          git push origin $DEFAULT_BRANCH