name: Scheduled Maintenance Tasks

on:
  schedule:
    # Runs every day at 02:00 UTC
    - cron: "0 2 * * *"
  workflow_dispatch:  # allows manual trigger

jobs:
  maintenance:
    name: Run Scheduled Maintenance
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js (adjust if your project uses another language)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run maintenance or backup script
      - name: Run scheduled maintenance script
        run: |
          echo "Starting maintenance task..."
          # Example: clean up temporary data or generate reports
          npm run maintenance || echo "No maintenance script found."

      # Optional: upload logs or results as artifacts
      - name: Upload maintenance logs
        uses: actions/upload-artifact@v4
        with:
          name: maintenance-logs
          path: logs/  # adjust if your script outputs logs elsewhere

      # Optional: notify team via email or Slack if something fails
      - name: Notify on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: " Scheduled Task Failed - Heavens Above"
          to: "devteam@xyzcorp.com"
          from: "GitHub Actions <no-reply@github.com>"
          body: "The scheduled maintenance job failed. Please check the GitHub Actions logs for details."
